- name: Clone latest version from github
  git:
    repo: 'https://github.com/adavisson/website.git'
    dest: /var/www/html/website/
    force: yes
  notify: Restart Apache
  become: true

- name: Copy .htaccess file for client side routing
  copy:
    src: ../files/.htaccess
    dest: /var/www/html/website/build/
  notify: Restart Apache
  become: true