- name: Clone latest version from github
  git:
    repo: https://github.com/adavisson/{{ item }}.git
    dest: /var/www/html/{{ item }}/
    force: yes
  with_items:
    - "website"
    - "crazy-tales"
    - "cfb-machine"
  notify: Restart Apache
  become: true

- name: Copy .htaccess file for client side routing
  copy:
    src: ../files/.htaccess
    dest: "{{ item }}"
  with_items:
    - "/var/www/html/website/build/"
    - "/var/www/html/crazy-tales/build/"
    - "/var/www/html/cfb-machine/build/"
  notify: Restart Apache
  become: true